Completed react-form-controls exercise. -Paul Glorioso
PaulGlorioso/rc1121-code-solutions pull request #123
Opened 2022-02-11 00:00 UTC by PaulGlorioso

![Screenshot 2022-02-10 124624](https://user-images.githubusercontent.com/93615301/153493821-ede31c54-42eb-4083-8e1e-afa155846303.jpg)

2022-02-11 01:53 UTC, scbowler requested changes
Looking good, just one update needed. Let me know if you have any questions.

2022-02-11 01:53 UTC, scbowler commented on react-form-controls/src/index.jsx
> +          <input type="email" value={this.state.value} onChange={this.handleChange}></input>
The `value` should be set by the property in state that is updated by on change, so it should be:
```JSX
value={this.state.email}
```

2022-03-04 01:53 UTC, PaulGlorioso commented
![Screenshot 2022-03-03 175123](https://user-images.githubusercontent.com/93615301/156684040-efef02f1-d323-45f5-9326-f276df65eb85.jpg)

2022-03-04 19:16 UTC, TimelikeClosure approved these changes

2022-03-04 23:33 UTC, merged