Completed javascript-carousel challenge. -Paul Glorioso
PaulGlorioso/rc1121-code-solutions pull request #63
Opened 2021-12-29 23:49 UTC by PaulGlorioso

![cycle](https://user-images.githubusercontent.com/93615301/147710995-13772080-2abb-40bf-b2aa-58f256facab3.gif)

2021-12-29 23:54 UTC, TimelikeClosure requested changes

2021-12-29 23:54 UTC, TimelikeClosure commented on javascript-carousel/main.js
> +setInterval(imgChange, 3000);
The automatic change timer should reset whenever the user manually changes the visible slide:

---

![image](https://user-images.githubusercontent.com/16143771/147711424-2f3a3b27-6354-4604-8d32-55701e6406fe.png)

2021-12-30 00:11 UTC, PaulGlorioso commented
![cycle2](https://user-images.githubusercontent.com/93615301/147711994-3b450dd8-a48e-4af0-a620-37c864fd4117.gif)

2021-12-30 00:19 UTC, TimelikeClosure approved these changes

2021-12-30 00:21 UTC, merged